# A workflow to run Bazel builds and tests.

name: precommit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
      - 'beta'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build+test ${{ matrix.name }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    strategy:
      fail-fast: ${{ github.event_name != 'workflow_dispatch' }}
      matrix:
        include:
          - { name: 'Linux x86_64 GCC',            os: 'ubuntu-24.04',   cc: gcc-14, cxx: g++-14,  config: }
          - { name: 'Linux x86_64 LLVM+libstdc++', os: 'ubuntu-24.04',   cc: clang,  cxx: clang++, config: --linkopt=-fuse-ld=lld }
          - { name: 'Linux x86_64 LLVM+libc++',    os: 'ubuntu-24.04',   cc: clang,  cxx: clang++, config: --config=libc++ --linkopt=-fuse-ld=lld }
          - { name: 'MacOS 15 x86_64 LLVM+libc++', os: 'macos-15-intel', cc: clang,  cxx: clang++, config: --config=libc++ }
          - { name: 'MacOS 26 x86_64 LLVM+libc++', os: 'macos-26-intel', cc: clang,  cxx: clang++, config: --config=libc++ }
          - { name: 'MacOS 15 ARM64 LLVM+libc++',  os: 'macos-15',       cc: clang,  cxx: clang++, config: --config=libc++ --macos_target_arch=arm64 }
          - { name: 'MacOS 26 ARM64 LLVM+libc++',  os: 'macos-26',       cc: clang,  cxx: clang++, config: --config=libc++ --macos_target_arch=arm64 }

    env:
      CC:  ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v3

      - name: install infrastructure (Linux)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get install libc++-dev libc++abi-dev python3-dev python3-numpy python3-packaging
          sudo ln -s /usr/lib/llvm-18/include/c++/v1 /usr/include/c++/v1

      - name: install infrastructure (MacOS)
        if: matrix.os == 'macos-15' || matrix.os == 'macos-15-intel' || matrix.os == 'macos-26' || matrix.os == 'macos-26-intel'
        run: brew install numpy python-packaging

      - name: build-lua5.1
        run: |
          bazel --bazelrc=.bazelrc build --config=lua5_1 ${{ matrix.config }} //...
      - name: test-lua5.1
        if: (!contains(matrix.config, 'arm64'))
        run: |
          bazel --bazelrc=.bazelrc test  --config=lua5_1 ${{ matrix.config }} --test_output=errors //...

      - name: build-lua5.2
        run: |
          bazel --bazelrc=.bazelrc build --config=lua5_2 ${{ matrix.config }} //...
      - name: test-lua5.2
        if: (!contains(matrix.config, 'arm64'))
        run: |
          bazel --bazelrc=.bazelrc test  --config=lua5_2 ${{ matrix.config }} --test_output=errors //...

      - name: build-luajit
        run: |
          bazel --bazelrc=.bazelrc build --config=luajit ${{ matrix.config }} //...
      - name: test-luajit
        if: (!contains(matrix.config, 'arm64'))
        run: |
          bazel --bazelrc=.bazelrc test  --config=luajit ${{ matrix.config }} --test_output=errors //...

      - name: build-luajit-internal_unwind
        run: |
          bazel --bazelrc=.bazelrc build --config=luajit ${{ matrix.config }} --copt=-fno-asynchronous-unwind-tables --luajit_external_unwinder=False //...
      - name: test-luajit-internal_unwind
        if: (!contains(matrix.config, 'arm64'))
        run: |
          bazel --bazelrc=.bazelrc test  --config=luajit ${{ matrix.config }} --copt=-fno-asynchronous-unwind-tables --luajit_external_unwinder=False --test_output=errors //...
